[package]
name = "serial-port-reader"
version = "0.1.2"
authors = ["signet-mob <signet.mob@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
serialport = "3.3"
structopt = "0.3"
toml = "0.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]
