= SerialReader
Todd Nguyen <todd.nguyen47@gmail.com>
:toc:

Read a serial port and display its output

== Prerequisites

On Debian-based systems like Ubuntu, you'll need to install `libudev-dev` and `pkg-config`

[source, bash]
----
sudo apt update
sudo apt install libudev-dev pkg-config
----

== How to Build Release version

[source, bash]
----
cargo build --release
----

== Confused?

Type in:

[source, bash]
----
./serial_port_reader_writer --help
----

== SerialConfig.toml

The `SerialConfig.toml` (or whatever name you named your config file) follows the settings
from the `serialport` https://docs.rs/serialport/3.3.0/serialport[repository]

== How to Read

* This program will use a file called `SerialConfig.toml` in the same directory as the executable by default. Ensure you have a `SerialConfig.toml` file. A sample `SerialConfig.toml` file is in the `src` folder.
* Build the release version.
* Make sure `SerialConfig.toml` is in the same directory as your executable.
* Run your executable with `./serial_port_reader_writer read`.

== How to Write

* Same as <<How to Read>>, except use the command `./serial_port_reader_writer write`

== How to Use - Advanced

* You can also specify a `.toml` file for the program to use by specifying the file path with the `--config` flag.
* Note that for `write` operations, `--commands` is an optional flag!

[source, bash]
----
./serial_port_reader_writer read --config <your_toml_file_path>
./serial_port_reader_writer write --config <your_toml_file_path> --commands <your_extra_commands_file_here>
----
