name: rust - cargo test

on:
  push:
    # On all branches for now
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test in Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Prerequisite install
        run: |
          sudo apt update
          sudo apt install libudev-dev pkg-config

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
